version: '3.9'
 
services:
  app:
    build:  .
   
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db

    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/posgressql


  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"
volumes:
  db_data:
   