version : '3'

services:
  mysql:
    image: mysql:5.7
    container_name: dev_mysql 
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 5678
      MYSQL_DATABASE: web_schema
    ports:
      - 3306:3306
    volumes:
      - my-datavolume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    restart: always
    ports:
      - 8184:80

wordpress:
    image: wordpress
    restart: always
    ports:
      - 8180:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html      
volumes:
  my-datavolume:
  wordpress:
